In [38]:
import numpy as np
np.set_printoptions(precision=2)

from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB


dataset = [[3, -2, 0], [1, 1, 1], [0, 2, 1], [-3, -4, 0], [-1, 5, 1], [3, 1, 0]]
X = dataset
y = dataset

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.20, random_state=5, stratify=None)   #20% for training, the rest is for testing

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)                    #learn the transformation (the mean and the stadard deviation for each variable) from the training set only!!
X_train2 = scaler.transform(X_train)   #apply the normalization to the training set
X_test2 = scaler.transform(X_test)     #must apply it to the test set if you applied to the training set
#clf2=KNeighborsClassifier(n_neighbors=1, metric='euclidean').fit(X_train2, y_train)
#print(clf2.score(X_test2, y_test))

#clf3=KNeighborsClassifier(n_neighbors=1, metric='manhattan').fit(X_train, y_train)
#print(clf3.score(X_test, y_test))


print(np.std(X_train, axis=0, ddof=0)**2)
V = np.var(X_train,axis=0)   #axis=0 means work with each column (all rows of a column is axis=0)
print(V)
params={'V': V}
print(params)
clf=KNeighborsClassifier(n_neighbors=1, metric='seuclidean', metric_params=params).fit(X_train, y_train)
#standardized euclidean measures the distance not on the original variables but on "normalized" variables
preds = clf.predict(X_test)
print(np.mean(preds==y_test))
#acc = clf.score(X_test, y_test)
#print(acc)

cnf_matrix = confusion_matrix(y_test, preds)
print(cnf_matrix)
FP = cnf_matrix.sum(axis=0) - np.diag(cnf_matrix)  #you said it is class2 but it was not class2
FN = cnf_matrix.sum(axis=1) - np.diag(cnf_matrix)
TP = np.diag(cnf_matrix)
TN = cnf_matrix.sum() - (FP + FN + TP)


#We'll continue from here on Fri. 
classes=[0,1,2]
for c in classes :
  #TP[i]= 
  #FP[i]=
  #????
  pass


test_count = len(y_test)
class_counts = np.array([sum(y_test==s) for s in range(3)])
print(class_counts)

FPRate = FP / (test_count - class_counts)
FNRate = FN / class_counts
TPRate = TP / class_counts
TNRate = TN / (test_count - class_counts)

print('TPRate',TPRate)
print('TNRate',TNRate)
print('FPRate',FPRate)
print('FNRate',FNRate)

Precision = TP/(TP+FP)
print('Precision', Precision)

Recall = TP/(TP+FN)
print('Recall', Recall)

from scipy import stats
print('F1 Score',stats.hmean([Precision, Recall]))  #Matthews correlation can be an alternative

from sklearn.metrics import classification_report
report = classification_report(y_test, preds)
print(report)

[0. 0. 0.]
[0. 0. 0.]
{'V': array([0., 0., 0.])}
0.13333333333333333


ValueError: ignored

In [0]:
print(confusion_matrix(y_test, preds))
#print(confusion_matrix(preds, y_test))
print(confusion_matrix(y_test, preds).sum(axis=0)) #how many examples are predicted to be of that class!!



[[40  0  0]
 [ 0 43  0]
 [ 0  2 35]]
[40 45 35]
