In [7]:
import numpy as np
a = np.array([[1,2,3,10],[4,5,6,7]])

print(a[0][1:3]) 
print(a[:1])
print(a[1,:])

b = a[0][1:3]

print(b)
print(b.T) #transpose attempt (doesn't work)


b = a[0][1:3].reshape((-1,1)) #Displays TRUE transpose
print(b)
print(a[0][1:3].shape)

[2 3]
[[ 1  2  3 10]]
[4 5 6 7]
[2 3]
[2 3]
[[2]
 [3]]
(2,)


In [9]:
import pandas as pd #good for reading files
df = pd.DataFrame(index=['A','B','C'], columns = ['x','y'])
df.loc['A']['y']=10
df.iloc[1][0]=20
df.head()

x    y
A  NaN   10
B   20  NaN
C  NaN  NaN

In [14]:
import pandas as pd
import numpy as np
df=pd.DataFrame(columns=['x','y'])
df['y']=np.random.randn(10)
df['x']=5
print(df)
print('\n')
print(df.mean())
print(df.std())
print('\n')

from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(df[['y']])

print('\n')
print(scaler.mean_)
print('\n')

df['z']=scaler.transform(df[['y']])
print(df)
print('\n')
print(df['y'].to_numpy())
print('\n')
print(df['z'].to_numpy())

   x         y
0  5  0.555820
1  5  1.211288
2  5  0.411381
3  5  2.811141
4  5 -0.678964
5  5  0.856842
6  5 -1.518984
7  5 -0.531613
8  5 -0.424205
9  5 -1.085778


x    5.000000
y    0.160693
dtype: float64
x    0.000000
y    1.279481
dtype: float64




[0.16069266]


   x         y         z
0  5  0.555820  0.325523
1  5  1.211288  0.865527
2  5  0.411381  0.206528
3  5  2.811141  2.183556
4  5 -0.678964 -0.691746
5  5  0.856842  0.573518
6  5 -1.518984 -1.383792
7  5 -0.531613 -0.570352
8  5 -0.424205 -0.481865
9  5 -1.085778 -1.026897


[ 0.55581975  1.211288    0.41138062  2.81114116 -0.6789644   0.85684161
 -1.51898437 -0.53161262 -0.42420519 -1.085778  ]


[ 0.32552307  0.86552662  0.20652776  2.18355596 -0.69174639  0.57351811
 -1.38379175 -0.57035151 -0.48186455 -1.02689731]


In [0]:
lr_acc_list = []
